import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

import {} from "next/font/google";
import Footer from "./components/Footer";

const josefinSans = Josefin_Sans({
  family: "Josefin Sans",
  weights: ["100", "300", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "eadavtian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={josefinSans.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
